# Generated by Django 5.1.7 on 2025-04-02 11:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('largura_maxima', models.IntegerField(default=1200)),
                ('espacamento', models.IntegerField(default=20)),
                ('colunas', models.IntegerField(default=12)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layouts',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('cor_primaria', models.CharField(default='#007bff', max_length=7)),
                ('cor_secundaria', models.CharField(default='#6c757d', max_length=7)),
                ('cor_fundo', models.CharField(default='#ffffff', max_length=7)),
                ('cor_texto', models.CharField(default='#212529', max_length=7)),
                ('fonte_principal', models.CharField(default='Arial', max_length=100)),
                ('tamanho_fonte', models.IntegerField(default=16)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('calendario', 'Calendário'), ('notas', 'Notas'), ('tarefas', 'Tarefas'), ('estatisticas', 'Estatísticas'), ('graficos', 'Gráficos')], max_length=50)),
                ('icone', models.CharField(help_text='Nome do ícone (FontAwesome)', max_length=50)),
                ('cor', models.CharField(help_text='Cor em formato hexadecimal', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DashboardUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=dict, help_text='Configuração do layout em JSON')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard do Usuário',
                'verbose_name_plural': 'Dashboards dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=10)),
                ('notificacoes_email', models.BooleanField(default=True)),
                ('notificacoes_push', models.BooleanField(default=True)),
                ('notificacoes_som', models.BooleanField(default=True)),
                ('tamanho_fonte', models.IntegerField(default=16, help_text='Tamanho da fonte em pixels', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)])),
                ('alto_contraste', models.BooleanField(default=False)),
                ('reducao_movimento', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacao.layout')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacao.tema')),
            ],
            options={
                'verbose_name': 'Preferência do Usuário',
                'verbose_name_plural': 'Preferências dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='WidgetDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_x', models.IntegerField(default=0)),
                ('posicao_y', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=1)),
                ('altura', models.IntegerField(default=1)),
                ('configuracao', models.JSONField(default=dict, help_text='Configurações específicas do widget')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizacao.dashboardusuario')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizacao.widget')),
            ],
            options={
                'verbose_name': 'Widget no Dashboard',
                'verbose_name_plural': 'Widgets no Dashboard',
                'ordering': ['posicao_y', 'posicao_x'],
                'unique_together': {('dashboard', 'widget')},
            },
        ),
        migrations.AddField(
            model_name='dashboardusuario',
            name='widgets',
            field=models.ManyToManyField(through='personalizacao.WidgetDashboard', to='personalizacao.widget'),
        ),
    ]
