# Generated by Django 5.1.7 on 2025-04-02 15:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='widgetdashboard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='layout',
            name='colunas',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='espacamento',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='largura_maxima',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='cor_fundo',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='cor_primaria',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='cor_secundaria',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='cor_texto',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='tamanho_fonte',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='icone',
        ),
        migrations.AddField(
            model_name='layout',
            name='configuracoes',
            field=models.TextField(default='{}', help_text='JSON com as configurações do layout'),
        ),
        migrations.AddField(
            model_name='layout',
            name='estrutura',
            field=models.TextField(default='{}', help_text='JSON com a estrutura do layout'),
        ),
        migrations.AddField(
            model_name='tema',
            name='cores_primarias',
            field=models.TextField(default='{"primaria": "#007bff", "secundaria": "#6c757d"}', help_text='JSON com as cores primárias do tema'),
        ),
        migrations.AddField(
            model_name='tema',
            name='cores_secundarias',
            field=models.TextField(default='{"primaria": "#28a745", "secundaria": "#dc3545"}', help_text='JSON com as cores secundárias do tema'),
        ),
        migrations.AddField(
            model_name='tema',
            name='fonte_secundaria',
            field=models.CharField(default='Open Sans', max_length=100),
        ),
        migrations.AddField(
            model_name='widget',
            name='configuracoes',
            field=models.TextField(default='{}', help_text='JSON com as configurações do widget'),
        ),
        migrations.AddField(
            model_name='widgetdashboard',
            name='configuracoes',
            field=models.TextField(default='{}', help_text='JSON com as configurações específicas do widget no dashboard'),
        ),
        migrations.AlterField(
            model_name='dashboardusuario',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacao.layout'),
        ),
        migrations.AlterField(
            model_name='dashboardusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preferenciausuario',
            name='tamanho_fonte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='medio', max_length=10),
        ),
        migrations.AlterField(
            model_name='preferenciausuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tema',
            name='fonte_principal',
            field=models.CharField(default='Roboto', max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='tipo',
            field=models.CharField(choices=[('calendario', 'Calendário'), ('notas', 'Notas'), ('tarefas', 'Tarefas'), ('estatisticas', 'Estatísticas'), ('graficos', 'Gráficos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='widgetdashboard',
            name='altura',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='widgetdashboard',
            name='largura',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='widgetdashboard',
            name='posicao_x',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='widgetdashboard',
            name='posicao_y',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='widgetdashboard',
            name='configuracao',
        ),
    ]
