# Generated by Django 5.1.7 on 2025-03-30 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Objetivo',
                'verbose_name_plural': 'Categorias de Objetivos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ListaVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Verificação',
                'verbose_name_plural': 'Listas de Verificação',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('lista_verificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='listas_verificacao.listaverificacao')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPredefinido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='listas_verificacao.categoriaobjetivo')),
            ],
            options={
                'verbose_name': 'Objetivo Predefinido',
                'verbose_name_plural': 'Objetivos Predefinidos',
                'ordering': ['categoria', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='listaverificacao',
            name='objetivos_predefinidos',
            field=models.ManyToManyField(blank=True, related_name='listas_verificacao', to='listas_verificacao.objetivopredefinido'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas_aluno', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='listaverificacao',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_verificacao', to='listas_verificacao.turma'),
        ),
        migrations.CreateModel(
            name='ProgressoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos_estado', models.JSONField(default=dict)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
                ('lista_verificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='listas_verificacao.listaverificacao')),
            ],
            options={
                'verbose_name': 'Progresso do Aluno',
                'verbose_name_plural': 'Progressos dos Alunos',
                'unique_together': {('aluno', 'lista_verificacao')},
            },
        ),
    ]
