# Generated by Django 5.1.7 on 2025-03-23 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DominioAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Domínio de Aprendizagem',
                'verbose_name_plural': 'Domínios de Aprendizagem',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField()),
                ('ano_escolar', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('disciplina', models.CharField(default='Português', max_length=50)),
                ('ordem', models.IntegerField(help_text='Ordem de apresentação dentro do domínio')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='listas_verificacao.dominioaprendizagem')),
            ],
            options={
                'verbose_name': 'Objetivo de Aprendizagem',
                'verbose_name_plural': 'Objetivos de Aprendizagem',
                'ordering': ['dominio', 'ordem'],
                'unique_together': {('dominio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='StatusObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído'), ('validado', 'Validado')], default='nao_iniciado', max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_objetivos', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_alunos', to='listas_verificacao.objetivoaprendizagem')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status de Objetivo',
                'verbose_name_plural': 'Status de Objetivos',
                'unique_together': {('aluno', 'objetivo')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.BooleanField(help_text='True para aprovado, False para reprovado')),
                ('comentarios', models.TextField(blank=True)),
                ('evidencias', models.TextField(help_text='Descrição das evidências que comprovam o domínio do objetivo')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='listas_verificacao.statusobjetivo')),
            ],
            options={
                'verbose_name': 'Registro de Avaliação',
                'verbose_name_plural': 'Registros de Avaliação',
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
