# Generated by Django 5.1.7 on 2025-03-30 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas_verificacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprendizagemEssencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('ano_escolar', models.PositiveIntegerField()),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aprendizagem Essencial',
                'verbose_name_plural': 'Aprendizagens Essenciais',
                'ordering': ['ano_escolar', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.AlterModelOptions(
            name='progressoaluno',
            options={'ordering': ['-data_atualizacao'], 'verbose_name': 'Progresso do Aluno', 'verbose_name_plural': 'Progressos dos Alunos'},
        ),
        migrations.RemoveField(
            model_name='listaverificacao',
            name='objetivos_predefinidos',
        ),
        migrations.AddField(
            model_name='listaverificacao',
            name='ano_escolar',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='progressoaluno',
            name='estado',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído'), ('dificuldade', 'Com Dificuldade')], default='nao_iniciado', max_length=20),
        ),
        migrations.AddField(
            model_name='progressoaluno',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='progressoaluno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listaverificacao',
            name='aprendizagens',
            field=models.ManyToManyField(related_name='listas_verificacao', to='listas_verificacao.aprendizagemessencial'),
        ),
        migrations.AddField(
            model_name='progressoaluno',
            name='aprendizagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='listas_verificacao.aprendizagemessencial'),
        ),
        migrations.AlterUniqueTogether(
            name='progressoaluno',
            unique_together={('aluno', 'lista_verificacao', 'aprendizagem')},
        ),
        migrations.AddField(
            model_name='aprendizagemessencial',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizagens', to='listas_verificacao.disciplina'),
        ),
        migrations.AddField(
            model_name='listaverificacao',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_verificacao', to='listas_verificacao.disciplina'),
        ),
        migrations.CreateModel(
            name='Domínio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='listas_verificacao.disciplina')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['ordem'],
                'unique_together': {('codigo', 'disciplina')},
            },
        ),
        migrations.AddField(
            model_name='aprendizagemessencial',
            name='dominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizagens', to='listas_verificacao.domínio'),
        ),
        migrations.CreateModel(
            name='Subdomínio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdominios', to='listas_verificacao.domínio')),
            ],
            options={
                'verbose_name': 'Subdomínio',
                'verbose_name_plural': 'Subdomínios',
                'ordering': ['ordem'],
                'unique_together': {('codigo', 'dominio')},
            },
        ),
        migrations.AddField(
            model_name='aprendizagemessencial',
            name='subdominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprendizagens', to='listas_verificacao.subdomínio'),
        ),
        migrations.RemoveField(
            model_name='progressoaluno',
            name='objetivos_estado',
        ),
        migrations.AlterUniqueTogether(
            name='aprendizagemessencial',
            unique_together={('codigo', 'disciplina', 'ano_escolar')},
        ),
    ]
