# Generated by Django 5.1.7 on 2025-03-23 00:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas_verificacao', '0002_populate_objetivos_6ano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominioaprendizagem',
            options={'verbose_name': 'Domínio de Aprendizagem', 'verbose_name_plural': 'Domínios de Aprendizagem'},
        ),
        migrations.AlterModelOptions(
            name='statusobjetivo',
            options={'verbose_name': 'Status do Objetivo', 'verbose_name_plural': 'Status dos Objetivos'},
        ),
        migrations.AlterUniqueTogether(
            name='objetivoaprendizagem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dominioaprendizagem',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='objetivoaprendizagem',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='objetivoaprendizagem',
            name='disciplina',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='objetivoaprendizagem',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroavaliacao',
            name='evidencias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registroavaliacao',
            name='resultado',
            field=models.BooleanField(),
        ),
        migrations.AlterUniqueTogether(
            name='objetivoaprendizagem',
            unique_together={('codigo', 'ano_escolar', 'disciplina')},
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_escolar', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('disciplina', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas_aluno', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'unique_together': {('nome', 'professor', 'ano_escolar', 'disciplina')},
            },
        ),
    ]
