# Generated by Django 5.1.7 on 2025-03-30 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas_verificacao', '0002_aprendizagemessencial_disciplina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('baixo_progresso', 'Baixo Progresso'), ('prazo_proximo', 'Prazo Próximo'), ('nova_duvida', 'Nova Dúvida'), ('conquista', 'Conquista'), ('feedback', 'Feedback'), ('lembrete', 'Lembrete'), ('resposta_duvida', 'Resposta à Dúvida'), ('confirmacao_pendente', 'Confirmação Pendente'), ('nova_dificuldade', 'Nova Dificuldade'), ('intervencao', 'Intervenção Pedagógica')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('aprendizagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='listas_verificacao.aprendizagemessencial')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('lista_verificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='listas_verificacao.listaverificacao')),
                ('progresso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='listas_verificacao.progressoaluno')),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['destinatario', 'lida'], name='listas_veri_destina_01bfc9_idx'), models.Index(fields=['tipo', 'data_criacao'], name='listas_veri_tipo_d5f5bc_idx')],
            },
        ),
    ]
