# Generated by Django 5.1.7 on 2025-04-02 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas_verificacao', '0004_configuracaonotificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('mais_trabalho', 'Mais Trabalho'), ('aguardando_avaliacao', 'Aguardando Avaliação'), ('avaliado_aprovado', 'Avaliado e Aprovado'), ('monitor_disponivel', 'Monitor Disponível')], default='mais_trabalho', max_length=20)),
                ('data_solicitacao_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_avaliador', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('progresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='listas_verificacao.progressoaluno')),
            ],
            options={
                'verbose_name': 'Avaliação de Aprendizagem',
                'verbose_name_plural': 'Avaliações de Aprendizagens',
            },
        ),
        migrations.CreateModel(
            name='ComentarioAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('autoavaliacao', 'Autoavaliação'), ('feedback_professor', 'Feedback do Professor'), ('comentario_monitor', 'Comentário de Monitor')], max_length=20)),
                ('texto', models.TextField()),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos_comentarios/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_feitos', to=settings.AUTH_USER_MODEL)),
                ('progresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='listas_verificacao.progressoaluno')),
            ],
            options={
                'verbose_name': 'Comentário de Aprendizagem',
                'verbose_name_plural': 'Comentários de Aprendizagens',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
