# Generated by Django 5.1.7 on 2025-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas_verificacao', '0005_avaliacaoaprendizagem_comentarioaprendizagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoaprendizagem',
            name='estado',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('mais_trabalho', 'Mais Trabalho'), ('aguardando_avaliacao', 'Aguardando Avaliação'), ('avaliado_aprovado', 'Avaliado e Aprovado'), ('monitor_disponivel', 'Monitor Disponível')], default='nao_iniciado', max_length=20),
        ),
    ]
