from django.urls import path
from . import views

app_name = 'listas_verificacao'

urlpatterns = [
    path('', views.lista_aluno, name='lista_aluno'),
    path('registrar-progresso/<int:lista_id>/', views.registrar_progresso, name='registrar_progresso'),
    path('dashboard/professor/', views.dashboard_professor, name='dashboard_professor'),
    path('dashboard/turma/<int:turma_id>/', views.dashboard_turma, name='dashboard_turma'),
    path('turmas/', views.lista_turmas, name='lista_turmas'),
    path('turmas/criar/', views.criar_turma, name='criar_turma'),
    path('turmas/<int:turma_id>/editar/', views.editar_turma, name='editar_turma'),
    path('turmas/<int:turma_id>/excluir/', views.excluir_turma, name='excluir_turma'),
    path('turmas/<int:turma_id>/adicionar-aluno/', views.adicionar_aluno, name='adicionar_aluno'),
    path('turmas/<int:turma_id>/remover-aluno/<int:aluno_id>/', views.remover_aluno, name='remover_aluno'),
    path('objetivo/<int:objetivo_id>/atualizar-status/', views.atualizar_status_objetivo, name='atualizar_status'),
    path('objetivo/<int:objetivo_id>/', views.detalhe_objetivo, name='detalhe_objetivo'),
    path('categorias/', views.gerenciar_categorias, name='gerenciar_categorias'),
    path('categorias/<int:categoria_id>/editar/', views.editar_categoria, name='editar_categoria'),
    path('categorias/<int:categoria_id>/excluir/', views.excluir_categoria, name='excluir_categoria'),
    path('objetivos-predefinidos/', views.gerenciar_objetivos_predefinidos, name='gerenciar_objetivos_predefinidos'),
    path('objetivos-predefinidos/<int:objetivo_id>/editar/', views.editar_objetivo_predefinido, name='editar_objetivo_predefinido'),
    path('objetivos-predefinidos/<int:objetivo_id>/excluir/', views.excluir_objetivo_predefinido, name='excluir_objetivo_predefinido'),
    path('listas/criar/', views.criar_lista_verificacao, name='criar_lista_verificacao'),
    path('listas/<int:lista_id>/editar/', views.editar_lista_verificacao, name='editar_lista_verificacao'),
    path('listas/<int:lista_id>/excluir/', views.excluir_lista_verificacao, name='excluir_lista_verificacao'),
    path('aprendizagens/', views.gerenciar_aprendizagens, name='gerenciar_aprendizagens'),
    path('aprendizagens/importar/', views.importar_aprendizagens, name='importar_aprendizagens'),
    path('aprendizagens/<int:aprendizagem_id>/editar/', views.editar_aprendizagem, name='editar_aprendizagem'),
    path('aprendizagens/<int:aprendizagem_id>/excluir/', views.excluir_aprendizagem, name='excluir_aprendizagem'),
    path('notificacoes/', views.lista_notificacoes, name='lista_notificacoes'),
    path('notificacoes/<int:notificacao_id>/marcar-lida/', views.marcar_notificacao_lida, name='marcar_notificacao_lida'),
    path('notificacoes/configurar/', views.configurar_notificacoes, name='configurar_notificacoes'),
    path('turma/<int:turma_id>/relatorio/', views.relatorio_progresso_turma, name='relatorio_progresso_turma'),
    path('turma/<int:turma_id>/aluno/<int:aluno_id>/relatorio/', views.relatorio_progresso_aluno, name='relatorio_progresso_aluno'),
    path('turma/<int:turma_id>/relatorio-tempo/', views.relatorio_tempo_conclusao, name='relatorio_tempo_conclusao'),
    path('turma/<int:turma_id>/relatorio-dificuldades/', views.relatorio_objetivos_dificeis, name='relatorio_objetivos_dificeis'),
    path('turma/<int:turma_id>/aluno/<int:aluno_id>/relatorio-dificuldades/', views.relatorio_dificuldades_aluno, name='relatorio_dificuldades_aluno'),
    path('turma/<int:turma_id>/relatorio-pendencias/', views.relatorio_aprendizagens_pendentes, name='relatorio_aprendizagens_pendentes'),
    path('turma/<int:turma_id>/relatorio-tendencias/', views.relatorio_tendencias_progresso, name='relatorio_tendencias_progresso'),
    path('turma/<int:turma_id>/relatorio-preditivo/', views.relatorio_analise_preditiva, name='relatorio_analise_preditiva'),
    path('turma/<int:turma_id>/relatorio-engajamento/', views.relatorio_engajamento, name='relatorio_engajamento'),
    path('turma/<int:turma_id>/relatorio-cooperacao/', views.relatorio_cooperacao, name='relatorio_cooperacao'),
    path('turma/<int:turma_id>/visualizacao-progresso/', views.visualizacao_progresso_turma, name='visualizacao_progresso_turma'),
    path('turma/<int:turma_id>/visualizacao-heatmap/', views.visualizacao_heatmap_atividade, name='visualizacao_heatmap_atividade'),
    path('turma/<int:turma_id>/visualizacao-tendencias/', views.visualizacao_tendencias, name='visualizacao_tendencias'),
    path('turma/<int:turma_id>/dashboard-interativo/', views.dashboard_interativo, name='dashboard_interativo'),
    path('turma/<int:turma_id>/dashboard-dados/', views.dashboard_dados, name='dashboard_dados'),
] 