# Generated by Django 5.1.7 on 2025-04-02 15:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('tamanho', models.BigIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('frequencia', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='diario', max_length=20)),
                ('hora_execucao', models.TimeField(default=datetime.time(0, 0))),
                ('manter_backups', models.IntegerField(default=7)),
                ('incluir_media', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_backup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
                'verbose_name_plural': 'Configurações de Backup',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoExportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_padrao', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel'), ('personalizado', 'Personalizado')], default='csv', max_length=20)),
                ('incluir_cabecalho', models.BooleanField(default=True)),
                ('separador', models.CharField(default=',', max_length=1)),
                ('encoding', models.CharField(default='utf-8', max_length=20)),
                ('compressao', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_exportacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Exportação',
                'verbose_name_plural': 'Configurações de Exportação',
            },
        ),
        migrations.CreateModel(
            name='Exportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel'), ('personalizado', 'Personalizado')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='exportacoes/')),
                ('tamanho', models.BigIntegerField(blank=True, null=True)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('descricao', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportação',
                'verbose_name_plural': 'Exportações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
