# Generated by Django 5.1.7 on 2025-03-20 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
        ('blog', '0002_class_userprofile_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_title', models.CharField(blank=True, max_length=200)),
                ('suggested_introduction', models.TextField(blank=True)),
                ('suggested_structure', models.JSONField(default=dict)),
                ('social_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='blog.post')),
            ],
            options={
                'verbose_name': 'Sugestão de IA',
                'verbose_name_plural': 'Sugestões de IA',
            },
        ),
    ]
